config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'tasks#index'
  post '/tasks', to: 'tasks#create'
  put '/tasks/:id', to: 'tasks#update'
  post '/tasks/:id', to: 'tasks#update'
  put '/tasks/:id/switch', to: 'tasks#switch'
  delete '/tasks/:id', to: 'tasks#destroy'
  delete '/tasks', to: 'tasks#reset'

  get '/about', to: 'about#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    validates :description, presence: true, length: { minimum: 3 }
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @open_tasks = Task.where(finished: false).reorder('updated_at').reverse_order
        @finished_tasks = Task.where(finished: true).reorder('updated_at').reverse_order
        @num_tasks = @open_tasks.length + @finished_tasks.length
        @open_percentage = @num_tasks > 0 ? 
            (@open_tasks.length.to_f / @num_tasks * 100).ceil : 0
        @finished_percentage = @num_tasks > 0 ? 100 - @open_percentage : 0
    end

    def create
        @task = Task.new(params.require(:task).permit(:description))
        @task.finished = false
        if @task.save
            redirect_to root_path
        else
            render js: "$('#alertCreateError').removeClass('d-none')"
        end
    end

    def update
        @task = Task.find(params[:id])
        @task.update(params.require(:task).permit(:description, :finished))
        redirect_to root_path
    end

    def switch
        @task = Task.find(params[:id])
        @task.finished = !@task.finished
        @task.save
        redirect_to root_path
    end

    def destroy
        @task = Task.find(params[:id])
        @task.destroy
        redirect_to root_path
    end

    def reset
        ActiveRecord::Base.connection.execute("TRUNCATE TABLE tasks RESTART IDENTITY;")
        redirect_to root_path
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/about/index.html.erb
<div class="container">
    <br>
    <h4>About this application</h4>
    <br>
    <p>
        This project is built with some cool technologies like
        <br>
        <a href="https://rubyonrails.org/" target="_blank">Ruby on Rails</a>
        <br>
        <a href="https://www.postgresql.org/" target="_blank">PostgreSQL</a>
        <br>
        <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>
        <br>
        <a href="https://jquery.com/" target="_blank">jQuery</a>
    </p>
    <p><a href="https://github.com/gabrielfern/ror-todo-list" target="_blank">
        <%= octicon "repo" %> Link to repository</a></p>
    <p>Made by <a href="https://github.com/gabrielfern" target="_blank">
        <%= octicon "mark-github" %> Gabriel Fernandes</a> with <%= octicon "heart" %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>To Do List</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <nav class="navbar navbar-dark navbar-expand-sm bg-secondary">
      <div class="container">
        <a class="navbar-brand" href="/"><img src="/favicon.ico">To Do List</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="/">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/about">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/tasks/_edit.html.erb
<div class="modal fade" id="editModal<%= task.id %>" tabindex="-1" role="dialog" aria-labelledby="editModal<%= task.id %>Label" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Edit Task #<%= task.id %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <%= hidden_field_tag "description_hidden#{task.id}", task.description%>
      <%= form_with model: task, url: "/tasks/#{task.id}", method: :put, id: "form#{task.id}" do |form| %>
        <div class="modal-body">
            <p>
                <%= form.label :description, class: 'font-weight-bold' %>
            <br>
                <%= form.text_area :description, class: 'form-control', form: "form#{task.id}", id: "description#{task.id}" %>
            </p>
            <div class="custom-control custom-checkbox">
                <%= form.check_box :finished, class: 'custom-control-input', id: "finished#{task.id}", form: "form#{task.id}" %>
                <label class="custom-control-label" for="finished<%= task.id %>">Is task finished?</label>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <%= form.submit 'Update',
                class: 'btn btn-primary', form: "form#{task.id}" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<script>
    $('#editModal<%= task.id %>').on('shown.bs.modal', () => $('#description<%= task.id %>').select())

    function editModal<%= task.id %>() {
        $('#editModal<%= task.id %>').modal()
        let decodedText = $('#description_hidden<%= task.id %>').val()
        $('#description<%= task.id %>').val(decodedText)
        $('#finished<%= task.id %>').prop('checked', <%= task.finished %>)
    }
</script>

app/views/tasks/index.html.erb
<div class="container">
    <br>
    <h4>Create Task</h4>
    <%= form_with scope: :task, url: tasks_path do |form| %>
        <p>
            <%= form.label :description, class: 'font-weight-bold' %>
        <br>
            <%= form.text_area :description, class: 'form-control' %>
        </p>
        <div id="alertCreateError" class="alert alert-danger alert-dismissible fade show d-none" role="alert">
            Task description must be at least 3 characters long
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <p>
            <%= form.submit 'Create', class: 'btn btn-outline-primary float-right' %>
        </p>
    <% end %>
    <p class="text-muted">
        Number of tasks: <%= @num_tasks %>
    </p>
    <input type="button" class="btn btn-danger" value="Reset tasks" onclick="resetTasks()">
    <br>

    <br>

    <h4>Open Tasks</h4>
    <div class="progress" style="height: 15px;">
        <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" role="progressbar"
            style="width: <%= @open_percentage %>%;">
                <%= @open_percentage %>%
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Task Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @open_tasks.each do |task| %>
                <%= render partial: "edit", locals: {task: task} %>
                <tr>
                    <th scope="row"><%= task.id %></th>
                    <td class="text-break" style="white-space: pre-wrap"><%= task.description %></td>
                    <td>
                        <%= link_to "/tasks/#{task.id}/switch",
                            method: :put,
                            remote: true,
                            style: "padding: 15px; display: inline-block;" do %>
                            <%= octicon "checklist" %>
                        <% end %>
                        <a href="javascript:" style="padding: 15px; display: inline-block;" onclick="editModal<%= task.id %>()">
                            <%= octicon "pencil" %>
                        </a>
                        <a href="javascript:" style="padding: 15px; display: inline-block;" onclick="deleteTask(<%= task.id %>)">
                            <%= octicon "trashcan" %>
                        </a>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <br>

    <h4>Finished Tasks</h4>
    <div class="progress" style="height: 15px;">
        <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
            style="width: <%= @finished_percentage %>%;">
                <%= @finished_percentage %>%
        </div>
    </div>
    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Task Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <% @finished_tasks.each do |task| %>
                <%= render partial: "edit", locals: {task: task} %>
                <tr>
                    <th scope="row"><%= task.id %></th>
                    <td class="text-break" style="white-space: pre-wrap"><%= task.description %></td>
                    <td>
                        <%= link_to "/tasks/#{task.id}/switch",
                            method: :put,
                            remote: true,
                            style: "padding: 15px; display: inline-block;" do %>
                            <%= octicon "checklist" %>
                        <% end %>
                        <a href="javascript:" style="padding: 15px; display: inline-block;" onclick="editModal<%= task.id %>()">
                            <%= octicon "pencil" %>
                        </a>
                        <a href="javascript:" style="padding: 15px; display: inline-block;" onclick="deleteTask(<%= task.id %>)">
                            <%= octicon "trashcan" %>
                        </a>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>
    <br>
</div>

<div class="modal fade" id="deleteTaskModal" tabindex="-1" role="dialog" aria-labelledby="deleteTaskModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h5>Are you sure you want to delete task #<span id="deleteTaskId"></span>?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= button_to 'Delete',
            "/tasks/",
            method: :delete,
            remote: true,
            class: 'btn btn-danger',
            id: 'deleteTaskButton',
            form: {id: 'deleteTaskLink'} %>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="resetTasksModal" tabindex="-1" role="dialog" aria-labelledby="resetTasksModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <h5>Are you sure you want to delete all tasks?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= button_to 'Reset tasks',
            "/tasks",
            method: :delete,
            remote: true,
            id: 'resetTasksButton',
            class: 'btn btn-danger' %>
      </div>
    </div>
  </div>
</div>

<script>
    $('#deleteTaskModal').on('shown.bs.modal', () => $('#deleteTaskButton').focus())
    $('#resetTasksModal').on('shown.bs.modal', () => $('#resetTasksButton').focus())

    function deleteTask(task) {
        $('#deleteTaskModal').modal()
        $('#deleteTaskId').text(task)
        $('#deleteTaskLink').prop('action', `/tasks/${task}`)
    }

    function resetTasks() {
        $('#resetTasksModal').modal()
    }
</script>